### ISSUE TITLE
Crash in production

### ISSUE THREAD

**Issue by itchingpixels** [prscX/react-native-morphing-text#1]
Hi!

Thanks for this library, it has been a great help for us.
We've rolled it out today to production, and facing this crash very frequently:
http://crashes.to/s/25d4475de0b

We have one issue that looks similar here:
https://github.com/hanks-zyh/HTextView/issues/64
or: https://github.com/hanks-zyh/HTextView/issues/56

Are there any suggestions how to resolve this?

Thank you!

**Comment by prscX** [comment]
Great to hear @itchingpixels that you are using it in production. Thanks for raising the issue and providing the reference.

Based on [HTextView: Issue - 64](https://github.com/hanks-zyh/HTextView/issues/64) I have made few changes in native source and looks like it is fixed now. 

Can you please verify by installing latest `v0.0.2`. Please let me know in case you still face the same issue.

Thanks
</ Pranav >

**Comment by itchingpixels** [comment]
great, thank you! we'll try this :)
