### ISSUE TITLE
iOS crash: Image not found

### ISSUE THREAD

**Issue by Nodonisko** [prscX/react-native-morphing-text#2]
Hi,
my app crash after start with this error message:

> dyld: Library not loaded: @rpath/libswiftCore.dylib
  Referenced from: /Users/daniel/Library/Developer/Xcode/DerivedData/brokertrust-ajqgrlzilpirhbcahswbodllebdu/Build/Products/Debug-iphonesimulator/LTMorphingLabel.framework/LTMorphingLabel
  Reason: image not found

**Comment by Nodonisko** [comment]
Sorry, my bad.

**Comment by javier-artiles** [comment]
@Nodonisko I'm facing the same issue. Could you explain how did you resolve it?

**Comment by prscX** [comment]
Thanks @javier-artiles for reporting the issue.

Have you followed **iOS** installation steps? Basically you need to add `LTMorphingLabel` to your app Embedded Binaries & Linked Frameworks and Libraries.  You can find the same steps on `README` as well.

Let us know in case it does not work.

Thanks
</ Pranav >

**Comment by javier-artiles** [comment]
Hi Pranav,

Thank you for following up on this. I did follow the README instructions for iOS. 
I just found that the error goes away after setting  "Build Settings > Build Options > Always Embed Swift Standard Libraries" to `true`. Found this through https://stackoverflow.com/a/39558803/2402158
Maybe this should be added to the README ?

**Comment by Nodonisko** [comment]
@javier-artiles There is multiple xcodeproj files, you need to choose right one I guess.
