### ISSUE TITLE
Update HTextView to 0.1.6

### ISSUE THREAD

**Issue by itchingpixels** [prscX/react-native-morphing-text#5]
Hi!

A few important crash fixes have been merged to HTextView, and it'd be great to use the updated version.

https://github.com/hanks-zyh/HTextView

Thank you :)

**Comment by prscX** [comment]
Thanks @itchingpixels for sharing the news.

I will update the version and push a release with the same.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @itchingpixels,

I have upgraded android native library and pushed a release `v0.0.4`.

Let me know incase you face any issues.

[V0.0.4](https://github.com/prscX/react-native-morphing-text/releases/tag/v0.0.4)

Thanks
</ Pranav >
